on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv --upgrade
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: execute tests
        run: ./test.sh
